# Site
repository: subhashvasarapu/modern-resume-theme
favicon: images/favicon.ico

# Personal info
name: Subhash Vasarapu
title: Azure Infrastructure Engineer
email: aryansubhash999@gmail.com
website: www.github.com/subhashvasarapu/Resume

darkmode: true
#future: true

# Social links
twitter_username: 8011753c8f87486
github_username:  subhashvasarapu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: subhash_vasarapu
linkedin_username: subhash-vasarapu-5a125795
# pinterest_username: jekyll
youtube_username: ZjSozeyzQDYjhfoi3aZzFQ
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Subhash and I'm Azure Infra & Netowrk administrator.I also have experience in DevOps and Ethical Hacking and web apps & Logic apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AZURE</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Boxing
   - Gaming
   - cycling
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
